// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bg_cpp_benchmark_matchup_random
Rcpp::List bg_cpp_benchmark_matchup_random(const Rcpp::List& board, const int n_games, const int max_turns, const std::string& player1_selection, const std::string& player2_selection, const int rollout_budget, const std::string& rollout_policy, const int max_rollout_turns, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_benchmark_matchup_random(SEXP boardSEXP, SEXP n_gamesSEXP, SEXP max_turnsSEXP, SEXP player1_selectionSEXP, SEXP player2_selectionSEXP, SEXP rollout_budgetSEXP, SEXP rollout_policySEXP, SEXP max_rollout_turnsSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const int >::type n_games(n_gamesSEXP);
    Rcpp::traits::input_parameter< const int >::type max_turns(max_turnsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type player1_selection(player1_selectionSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type player2_selection(player2_selectionSEXP);
    Rcpp::traits::input_parameter< const int >::type rollout_budget(rollout_budgetSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type rollout_policy(rollout_policySEXP);
    Rcpp::traits::input_parameter< const int >::type max_rollout_turns(max_rollout_turnsSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_benchmark_matchup_random(board, n_games, max_turns, player1_selection, player2_selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_benchmark_matchup_scripted
Rcpp::List bg_cpp_benchmark_matchup_scripted(const Rcpp::List& board, const Rcpp::List& rolls, const int n_games, const int max_turns, const std::string& player1_selection, const std::string& player2_selection, const int rollout_budget, const std::string& rollout_policy, const int max_rollout_turns, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_benchmark_matchup_scripted(SEXP boardSEXP, SEXP rollsSEXP, SEXP n_gamesSEXP, SEXP max_turnsSEXP, SEXP player1_selectionSEXP, SEXP player2_selectionSEXP, SEXP rollout_budgetSEXP, SEXP rollout_policySEXP, SEXP max_rollout_turnsSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type rolls(rollsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_games(n_gamesSEXP);
    Rcpp::traits::input_parameter< const int >::type max_turns(max_turnsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type player1_selection(player1_selectionSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type player2_selection(player2_selectionSEXP);
    Rcpp::traits::input_parameter< const int >::type rollout_budget(rollout_budgetSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type rollout_policy(rollout_policySEXP);
    Rcpp::traits::input_parameter< const int >::type max_rollout_turns(max_rollout_turnsSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_benchmark_matchup_scripted(board, rolls, n_games, max_turns, player1_selection, player2_selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_benchmark_move_evaluators
Rcpp::List bg_cpp_benchmark_move_evaluators(const Rcpp::List& cases, const std::vector<std::string>& methods, const std::string& reference_method, const int rollout_budget, const std::string& rollout_policy, const int max_rollout_turns, const int reference_rollout_budget, const std::string& reference_rollout_policy, const int reference_max_rollout_turns, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_benchmark_move_evaluators(SEXP casesSEXP, SEXP methodsSEXP, SEXP reference_methodSEXP, SEXP rollout_budgetSEXP, SEXP rollout_policySEXP, SEXP max_rollout_turnsSEXP, SEXP reference_rollout_budgetSEXP, SEXP reference_rollout_policySEXP, SEXP reference_max_rollout_turnsSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type cases(casesSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type methods(methodsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type reference_method(reference_methodSEXP);
    Rcpp::traits::input_parameter< const int >::type rollout_budget(rollout_budgetSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type rollout_policy(rollout_policySEXP);
    Rcpp::traits::input_parameter< const int >::type max_rollout_turns(max_rollout_turnsSEXP);
    Rcpp::traits::input_parameter< const int >::type reference_rollout_budget(reference_rollout_budgetSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type reference_rollout_policy(reference_rollout_policySEXP);
    Rcpp::traits::input_parameter< const int >::type reference_max_rollout_turns(reference_max_rollout_turnsSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_benchmark_move_evaluators(cases, methods, reference_method, rollout_budget, rollout_policy, max_rollout_turns, reference_rollout_budget, reference_rollout_policy, reference_max_rollout_turns, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_board_initial
Rcpp::List bg_cpp_board_initial(const int turn);
RcppExport SEXP _backgammonr_bg_cpp_board_initial(SEXP turnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type turn(turnSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_board_initial(turn));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_board_clone
Rcpp::List bg_cpp_board_clone(const Rcpp::List& board);
RcppExport SEXP _backgammonr_bg_cpp_board_clone(SEXP boardSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_board_clone(board));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_board_validate
Rcpp::List bg_cpp_board_validate(const Rcpp::List& board);
RcppExport SEXP _backgammonr_bg_cpp_board_validate(SEXP boardSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_board_validate(board));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_roll_create
Rcpp::List bg_cpp_roll_create(const int die1, const int die2);
RcppExport SEXP _backgammonr_bg_cpp_roll_create(SEXP die1SEXP, SEXP die2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type die1(die1SEXP);
    Rcpp::traits::input_parameter< const int >::type die2(die2SEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_roll_create(die1, die2));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_roll_dice
Rcpp::List bg_cpp_roll_dice(const int n, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_roll_dice(SEXP nSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_roll_dice(n, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_terminal_score_class
std::string bg_cpp_terminal_score_class(const Rcpp::List& board, const int perspective_player);
RcppExport SEXP _backgammonr_bg_cpp_terminal_score_class(SEXP boardSEXP, SEXP perspective_playerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const int >::type perspective_player(perspective_playerSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_terminal_score_class(board, perspective_player));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_apply_move_sequence
Rcpp::List bg_cpp_apply_move_sequence(const Rcpp::List& board, const Rcpp::List& move_sequence);
RcppExport SEXP _backgammonr_bg_cpp_apply_move_sequence(SEXP boardSEXP, SEXP move_sequenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type move_sequence(move_sequenceSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_apply_move_sequence(board, move_sequence));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_play_turn_with_roll
Rcpp::List bg_cpp_play_turn_with_roll(const Rcpp::List& board, const Rcpp::List& roll, const std::string& selection, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_play_turn_with_roll(SEXP boardSEXP, SEXP rollSEXP, SEXP selectionSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type roll(rollSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type selection(selectionSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_play_turn_with_roll(board, roll, selection, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_play_turn_random
Rcpp::List bg_cpp_play_turn_random(const Rcpp::List& board, const std::string& selection, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_play_turn_random(SEXP boardSEXP, SEXP selectionSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type selection(selectionSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_play_turn_random(board, selection, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_play_game_random
Rcpp::List bg_cpp_play_game_random(const Rcpp::List& board, const int max_turns, const std::string& selection, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_play_game_random(SEXP boardSEXP, SEXP max_turnsSEXP, SEXP selectionSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const int >::type max_turns(max_turnsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type selection(selectionSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_play_game_random(board, max_turns, selection, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_play_game_scripted
Rcpp::List bg_cpp_play_game_scripted(const Rcpp::List& board, const Rcpp::List& rolls, const int max_turns, const std::string& selection, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_play_game_scripted(SEXP boardSEXP, SEXP rollsSEXP, SEXP max_turnsSEXP, SEXP selectionSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type rolls(rollsSEXP);
    Rcpp::traits::input_parameter< const int >::type max_turns(max_turnsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type selection(selectionSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_play_game_scripted(board, rolls, max_turns, selection, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_play_game_matchup_random
Rcpp::List bg_cpp_play_game_matchup_random(const Rcpp::List& board, const int max_turns, const std::string& player1_selection, const std::string& player2_selection, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_play_game_matchup_random(SEXP boardSEXP, SEXP max_turnsSEXP, SEXP player1_selectionSEXP, SEXP player2_selectionSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const int >::type max_turns(max_turnsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type player1_selection(player1_selectionSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type player2_selection(player2_selectionSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_play_game_matchup_random(board, max_turns, player1_selection, player2_selection, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_play_game_matchup_scripted
Rcpp::List bg_cpp_play_game_matchup_scripted(const Rcpp::List& board, const Rcpp::List& rolls, const int max_turns, const std::string& player1_selection, const std::string& player2_selection, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_play_game_matchup_scripted(SEXP boardSEXP, SEXP rollsSEXP, SEXP max_turnsSEXP, SEXP player1_selectionSEXP, SEXP player2_selectionSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type rolls(rollsSEXP);
    Rcpp::traits::input_parameter< const int >::type max_turns(max_turnsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type player1_selection(player1_selectionSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type player2_selection(player2_selectionSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_play_game_matchup_scripted(board, rolls, max_turns, player1_selection, player2_selection, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_play_turn_with_roll_rollout
Rcpp::List bg_cpp_play_turn_with_roll_rollout(const Rcpp::List& board, const Rcpp::List& roll, const std::string& selection, const int rollout_budget, const std::string& rollout_policy, const int max_rollout_turns, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_play_turn_with_roll_rollout(SEXP boardSEXP, SEXP rollSEXP, SEXP selectionSEXP, SEXP rollout_budgetSEXP, SEXP rollout_policySEXP, SEXP max_rollout_turnsSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type roll(rollSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type selection(selectionSEXP);
    Rcpp::traits::input_parameter< const int >::type rollout_budget(rollout_budgetSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type rollout_policy(rollout_policySEXP);
    Rcpp::traits::input_parameter< const int >::type max_rollout_turns(max_rollout_turnsSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_play_turn_with_roll_rollout(board, roll, selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_play_turn_random_rollout
Rcpp::List bg_cpp_play_turn_random_rollout(const Rcpp::List& board, const std::string& selection, const int rollout_budget, const std::string& rollout_policy, const int max_rollout_turns, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_play_turn_random_rollout(SEXP boardSEXP, SEXP selectionSEXP, SEXP rollout_budgetSEXP, SEXP rollout_policySEXP, SEXP max_rollout_turnsSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type selection(selectionSEXP);
    Rcpp::traits::input_parameter< const int >::type rollout_budget(rollout_budgetSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type rollout_policy(rollout_policySEXP);
    Rcpp::traits::input_parameter< const int >::type max_rollout_turns(max_rollout_turnsSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_play_turn_random_rollout(board, selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_play_game_random_rollout
Rcpp::List bg_cpp_play_game_random_rollout(const Rcpp::List& board, const int max_turns, const std::string& selection, const int rollout_budget, const std::string& rollout_policy, const int max_rollout_turns, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_play_game_random_rollout(SEXP boardSEXP, SEXP max_turnsSEXP, SEXP selectionSEXP, SEXP rollout_budgetSEXP, SEXP rollout_policySEXP, SEXP max_rollout_turnsSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const int >::type max_turns(max_turnsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type selection(selectionSEXP);
    Rcpp::traits::input_parameter< const int >::type rollout_budget(rollout_budgetSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type rollout_policy(rollout_policySEXP);
    Rcpp::traits::input_parameter< const int >::type max_rollout_turns(max_rollout_turnsSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_play_game_random_rollout(board, max_turns, selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_play_game_scripted_rollout
Rcpp::List bg_cpp_play_game_scripted_rollout(const Rcpp::List& board, const Rcpp::List& rolls, const int max_turns, const std::string& selection, const int rollout_budget, const std::string& rollout_policy, const int max_rollout_turns, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_play_game_scripted_rollout(SEXP boardSEXP, SEXP rollsSEXP, SEXP max_turnsSEXP, SEXP selectionSEXP, SEXP rollout_budgetSEXP, SEXP rollout_policySEXP, SEXP max_rollout_turnsSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type rolls(rollsSEXP);
    Rcpp::traits::input_parameter< const int >::type max_turns(max_turnsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type selection(selectionSEXP);
    Rcpp::traits::input_parameter< const int >::type rollout_budget(rollout_budgetSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type rollout_policy(rollout_policySEXP);
    Rcpp::traits::input_parameter< const int >::type max_rollout_turns(max_rollout_turnsSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_play_game_scripted_rollout(board, rolls, max_turns, selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_play_game_matchup_random_rollout
Rcpp::List bg_cpp_play_game_matchup_random_rollout(const Rcpp::List& board, const int max_turns, const std::string& player1_selection, const std::string& player2_selection, const int rollout_budget, const std::string& rollout_policy, const int max_rollout_turns, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_play_game_matchup_random_rollout(SEXP boardSEXP, SEXP max_turnsSEXP, SEXP player1_selectionSEXP, SEXP player2_selectionSEXP, SEXP rollout_budgetSEXP, SEXP rollout_policySEXP, SEXP max_rollout_turnsSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const int >::type max_turns(max_turnsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type player1_selection(player1_selectionSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type player2_selection(player2_selectionSEXP);
    Rcpp::traits::input_parameter< const int >::type rollout_budget(rollout_budgetSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type rollout_policy(rollout_policySEXP);
    Rcpp::traits::input_parameter< const int >::type max_rollout_turns(max_rollout_turnsSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_play_game_matchup_random_rollout(board, max_turns, player1_selection, player2_selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_play_game_matchup_scripted_rollout
Rcpp::List bg_cpp_play_game_matchup_scripted_rollout(const Rcpp::List& board, const Rcpp::List& rolls, const int max_turns, const std::string& player1_selection, const std::string& player2_selection, const int rollout_budget, const std::string& rollout_policy, const int max_rollout_turns, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_play_game_matchup_scripted_rollout(SEXP boardSEXP, SEXP rollsSEXP, SEXP max_turnsSEXP, SEXP player1_selectionSEXP, SEXP player2_selectionSEXP, SEXP rollout_budgetSEXP, SEXP rollout_policySEXP, SEXP max_rollout_turnsSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type rolls(rollsSEXP);
    Rcpp::traits::input_parameter< const int >::type max_turns(max_turnsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type player1_selection(player1_selectionSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type player2_selection(player2_selectionSEXP);
    Rcpp::traits::input_parameter< const int >::type rollout_budget(rollout_budgetSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type rollout_policy(rollout_policySEXP);
    Rcpp::traits::input_parameter< const int >::type max_rollout_turns(max_rollout_turnsSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_play_game_matchup_scripted_rollout(board, rolls, max_turns, player1_selection, player2_selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_move_step_create
Rcpp::List bg_cpp_move_step_create(const int from, const int to, const int die, const bool hit);
RcppExport SEXP _backgammonr_bg_cpp_move_step_create(SEXP fromSEXP, SEXP toSEXP, SEXP dieSEXP, SEXP hitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< const int >::type to(toSEXP);
    Rcpp::traits::input_parameter< const int >::type die(dieSEXP);
    Rcpp::traits::input_parameter< const bool >::type hit(hitSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_move_step_create(from, to, die, hit));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_move_sequence_create
Rcpp::List bg_cpp_move_sequence_create(const int player, const Rcpp::List& steps);
RcppExport SEXP _backgammonr_bg_cpp_move_sequence_create(SEXP playerSEXP, SEXP stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type player(playerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type steps(stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_move_sequence_create(player, steps));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_move_sequence_create_with_roll
Rcpp::List bg_cpp_move_sequence_create_with_roll(const int player, const Rcpp::List& steps, const Rcpp::List& roll);
RcppExport SEXP _backgammonr_bg_cpp_move_sequence_create_with_roll(SEXP playerSEXP, SEXP stepsSEXP, SEXP rollSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type player(playerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type steps(stepsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type roll(rollSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_move_sequence_create_with_roll(player, steps, roll));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_legal_moves
Rcpp::List bg_cpp_legal_moves(const Rcpp::List& board, const int player, const Rcpp::List& roll);
RcppExport SEXP _backgammonr_bg_cpp_legal_moves(SEXP boardSEXP, SEXP playerSEXP, SEXP rollSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const int >::type player(playerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type roll(rollSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_legal_moves(board, player, roll));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_random_move_choice
Rcpp::List bg_cpp_random_move_choice(const Rcpp::List& legal_moves, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_random_move_choice(SEXP legal_movesSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type legal_moves(legal_movesSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_random_move_choice(legal_moves, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_heuristic_board_score
double bg_cpp_heuristic_board_score(const Rcpp::List& board, const int player, const std::string& selection);
RcppExport SEXP _backgammonr_bg_cpp_heuristic_board_score(SEXP boardSEXP, SEXP playerSEXP, SEXP selectionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const int >::type player(playerSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type selection(selectionSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_heuristic_board_score(board, player, selection));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_heuristic_board_features
Rcpp::List bg_cpp_heuristic_board_features(const Rcpp::List& board, const int player);
RcppExport SEXP _backgammonr_bg_cpp_heuristic_board_features(SEXP boardSEXP, SEXP playerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const int >::type player(playerSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_heuristic_board_features(board, player));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_heuristic_move_choice
Rcpp::List bg_cpp_heuristic_move_choice(const Rcpp::List& board, const Rcpp::List& legal_moves, const std::string& selection);
RcppExport SEXP _backgammonr_bg_cpp_heuristic_move_choice(SEXP boardSEXP, SEXP legal_movesSEXP, SEXP selectionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type legal_moves(legal_movesSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type selection(selectionSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_heuristic_move_choice(board, legal_moves, selection));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_thompson_rollout_move_evaluate
Rcpp::DataFrame bg_cpp_thompson_rollout_move_evaluate(const Rcpp::List& board, const Rcpp::List& legal_moves, const int rollout_budget, const std::string& rollout_policy, const int max_rollout_turns, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_thompson_rollout_move_evaluate(SEXP boardSEXP, SEXP legal_movesSEXP, SEXP rollout_budgetSEXP, SEXP rollout_policySEXP, SEXP max_rollout_turnsSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type legal_moves(legal_movesSEXP);
    Rcpp::traits::input_parameter< const int >::type rollout_budget(rollout_budgetSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type rollout_policy(rollout_policySEXP);
    Rcpp::traits::input_parameter< const int >::type max_rollout_turns(max_rollout_turnsSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_thompson_rollout_move_evaluate(board, legal_moves, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_thompson_rollout_move_choice
Rcpp::List bg_cpp_thompson_rollout_move_choice(const Rcpp::List& board, const Rcpp::List& legal_moves, const int rollout_budget, const std::string& rollout_policy, const int max_rollout_turns, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_thompson_rollout_move_choice(SEXP boardSEXP, SEXP legal_movesSEXP, SEXP rollout_budgetSEXP, SEXP rollout_policySEXP, SEXP max_rollout_turnsSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type legal_moves(legal_movesSEXP);
    Rcpp::traits::input_parameter< const int >::type rollout_budget(rollout_budgetSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type rollout_policy(rollout_policySEXP);
    Rcpp::traits::input_parameter< const int >::type max_rollout_turns(max_rollout_turnsSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_thompson_rollout_move_choice(board, legal_moves, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_rollout_move_evaluate
Rcpp::DataFrame bg_cpp_rollout_move_evaluate(const Rcpp::List& board, const Rcpp::List& legal_moves, const int rollout_budget, const std::string& rollout_policy, const int max_rollout_turns, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_rollout_move_evaluate(SEXP boardSEXP, SEXP legal_movesSEXP, SEXP rollout_budgetSEXP, SEXP rollout_policySEXP, SEXP max_rollout_turnsSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type legal_moves(legal_movesSEXP);
    Rcpp::traits::input_parameter< const int >::type rollout_budget(rollout_budgetSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type rollout_policy(rollout_policySEXP);
    Rcpp::traits::input_parameter< const int >::type max_rollout_turns(max_rollout_turnsSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_rollout_move_evaluate(board, legal_moves, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_rollout_move_choice
Rcpp::List bg_cpp_rollout_move_choice(const Rcpp::List& board, const Rcpp::List& legal_moves, const int rollout_budget, const std::string& rollout_policy, const int max_rollout_turns, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_rollout_move_choice(SEXP boardSEXP, SEXP legal_movesSEXP, SEXP rollout_budgetSEXP, SEXP rollout_policySEXP, SEXP max_rollout_turnsSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type legal_moves(legal_movesSEXP);
    Rcpp::traits::input_parameter< const int >::type rollout_budget(rollout_budgetSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type rollout_policy(rollout_policySEXP);
    Rcpp::traits::input_parameter< const int >::type max_rollout_turns(max_rollout_turnsSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_rollout_move_choice(board, legal_moves, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_simulate_matchup_random
Rcpp::List bg_cpp_simulate_matchup_random(const Rcpp::List& board, const int n_games, const int max_turns, const std::string& player1_selection, const std::string& player2_selection, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_simulate_matchup_random(SEXP boardSEXP, SEXP n_gamesSEXP, SEXP max_turnsSEXP, SEXP player1_selectionSEXP, SEXP player2_selectionSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const int >::type n_games(n_gamesSEXP);
    Rcpp::traits::input_parameter< const int >::type max_turns(max_turnsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type player1_selection(player1_selectionSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type player2_selection(player2_selectionSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_simulate_matchup_random(board, n_games, max_turns, player1_selection, player2_selection, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_simulate_matchup_scripted
Rcpp::List bg_cpp_simulate_matchup_scripted(const Rcpp::List& board, const Rcpp::List& rolls, const int n_games, const int max_turns, const std::string& player1_selection, const std::string& player2_selection, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_simulate_matchup_scripted(SEXP boardSEXP, SEXP rollsSEXP, SEXP n_gamesSEXP, SEXP max_turnsSEXP, SEXP player1_selectionSEXP, SEXP player2_selectionSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type rolls(rollsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_games(n_gamesSEXP);
    Rcpp::traits::input_parameter< const int >::type max_turns(max_turnsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type player1_selection(player1_selectionSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type player2_selection(player2_selectionSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_simulate_matchup_scripted(board, rolls, n_games, max_turns, player1_selection, player2_selection, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_simulate_matchup_random_rollout
Rcpp::List bg_cpp_simulate_matchup_random_rollout(const Rcpp::List& board, const int n_games, const int max_turns, const std::string& player1_selection, const std::string& player2_selection, const int rollout_budget, const std::string& rollout_policy, const int max_rollout_turns, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_simulate_matchup_random_rollout(SEXP boardSEXP, SEXP n_gamesSEXP, SEXP max_turnsSEXP, SEXP player1_selectionSEXP, SEXP player2_selectionSEXP, SEXP rollout_budgetSEXP, SEXP rollout_policySEXP, SEXP max_rollout_turnsSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const int >::type n_games(n_gamesSEXP);
    Rcpp::traits::input_parameter< const int >::type max_turns(max_turnsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type player1_selection(player1_selectionSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type player2_selection(player2_selectionSEXP);
    Rcpp::traits::input_parameter< const int >::type rollout_budget(rollout_budgetSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type rollout_policy(rollout_policySEXP);
    Rcpp::traits::input_parameter< const int >::type max_rollout_turns(max_rollout_turnsSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_simulate_matchup_random_rollout(board, n_games, max_turns, player1_selection, player2_selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_simulate_matchup_scripted_rollout
Rcpp::List bg_cpp_simulate_matchup_scripted_rollout(const Rcpp::List& board, const Rcpp::List& rolls, const int n_games, const int max_turns, const std::string& player1_selection, const std::string& player2_selection, const int rollout_budget, const std::string& rollout_policy, const int max_rollout_turns, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_simulate_matchup_scripted_rollout(SEXP boardSEXP, SEXP rollsSEXP, SEXP n_gamesSEXP, SEXP max_turnsSEXP, SEXP player1_selectionSEXP, SEXP player2_selectionSEXP, SEXP rollout_budgetSEXP, SEXP rollout_policySEXP, SEXP max_rollout_turnsSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type rolls(rollsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_games(n_gamesSEXP);
    Rcpp::traits::input_parameter< const int >::type max_turns(max_turnsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type player1_selection(player1_selectionSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type player2_selection(player2_selectionSEXP);
    Rcpp::traits::input_parameter< const int >::type rollout_budget(rollout_budgetSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type rollout_policy(rollout_policySEXP);
    Rcpp::traits::input_parameter< const int >::type max_rollout_turns(max_rollout_turnsSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_simulate_matchup_scripted_rollout(board, rolls, n_games, max_turns, player1_selection, player2_selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_allocation_evaluate
Rcpp::List bg_cpp_allocation_evaluate(const Rcpp::List& board, const Rcpp::List& legal_moves, const std::string& method, const int total_budget, const std::string& rollout_policy, const int max_rollout_turns, const double unresolved_value, const int initial_allocations, const double ucb_exploration, const double prior_alpha, const double prior_beta, const std::string& dice_mode, const bool crn, const bool fast_diagnostics, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_allocation_evaluate(SEXP boardSEXP, SEXP legal_movesSEXP, SEXP methodSEXP, SEXP total_budgetSEXP, SEXP rollout_policySEXP, SEXP max_rollout_turnsSEXP, SEXP unresolved_valueSEXP, SEXP initial_allocationsSEXP, SEXP ucb_explorationSEXP, SEXP prior_alphaSEXP, SEXP prior_betaSEXP, SEXP dice_modeSEXP, SEXP crnSEXP, SEXP fast_diagnosticsSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type legal_moves(legal_movesSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const int >::type total_budget(total_budgetSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type rollout_policy(rollout_policySEXP);
    Rcpp::traits::input_parameter< const int >::type max_rollout_turns(max_rollout_turnsSEXP);
    Rcpp::traits::input_parameter< const double >::type unresolved_value(unresolved_valueSEXP);
    Rcpp::traits::input_parameter< const int >::type initial_allocations(initial_allocationsSEXP);
    Rcpp::traits::input_parameter< const double >::type ucb_exploration(ucb_explorationSEXP);
    Rcpp::traits::input_parameter< const double >::type prior_alpha(prior_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type prior_beta(prior_betaSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dice_mode(dice_modeSEXP);
    Rcpp::traits::input_parameter< const bool >::type crn(crnSEXP);
    Rcpp::traits::input_parameter< const bool >::type fast_diagnostics(fast_diagnosticsSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_allocation_evaluate(board, legal_moves, method, total_budget, rollout_policy, max_rollout_turns, unresolved_value, initial_allocations, ucb_exploration, prior_alpha, prior_beta, dice_mode, crn, fast_diagnostics, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_allocation_evaluate_trace
Rcpp::List bg_cpp_allocation_evaluate_trace(const Rcpp::List& board, const Rcpp::List& legal_moves, const std::string& method, const int total_budget, const std::string& rollout_policy, const int max_rollout_turns, const double unresolved_value, const int initial_allocations, const double ucb_exploration, const double prior_alpha, const double prior_beta, const std::string& dice_mode, const bool crn, const bool fast_diagnostics, const int trace_every, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_allocation_evaluate_trace(SEXP boardSEXP, SEXP legal_movesSEXP, SEXP methodSEXP, SEXP total_budgetSEXP, SEXP rollout_policySEXP, SEXP max_rollout_turnsSEXP, SEXP unresolved_valueSEXP, SEXP initial_allocationsSEXP, SEXP ucb_explorationSEXP, SEXP prior_alphaSEXP, SEXP prior_betaSEXP, SEXP dice_modeSEXP, SEXP crnSEXP, SEXP fast_diagnosticsSEXP, SEXP trace_everySEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type legal_moves(legal_movesSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const int >::type total_budget(total_budgetSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type rollout_policy(rollout_policySEXP);
    Rcpp::traits::input_parameter< const int >::type max_rollout_turns(max_rollout_turnsSEXP);
    Rcpp::traits::input_parameter< const double >::type unresolved_value(unresolved_valueSEXP);
    Rcpp::traits::input_parameter< const int >::type initial_allocations(initial_allocationsSEXP);
    Rcpp::traits::input_parameter< const double >::type ucb_exploration(ucb_explorationSEXP);
    Rcpp::traits::input_parameter< const double >::type prior_alpha(prior_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type prior_beta(prior_betaSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dice_mode(dice_modeSEXP);
    Rcpp::traits::input_parameter< const bool >::type crn(crnSEXP);
    Rcpp::traits::input_parameter< const bool >::type fast_diagnostics(fast_diagnosticsSEXP);
    Rcpp::traits::input_parameter< const int >::type trace_every(trace_everySEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_allocation_evaluate_trace(board, legal_moves, method, total_budget, rollout_policy, max_rollout_turns, unresolved_value, initial_allocations, ucb_exploration, prior_alpha, prior_beta, dice_mode, crn, fast_diagnostics, trace_every, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_profile_rollout_runtime
Rcpp::List bg_cpp_profile_rollout_runtime(const Rcpp::List& board, const Rcpp::List& roll, const int legal_reps, const int apply_reps, const int one_rollout_reps, const int total_budget, const std::string& rollout_policy, const int max_rollout_turns, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_profile_rollout_runtime(SEXP boardSEXP, SEXP rollSEXP, SEXP legal_repsSEXP, SEXP apply_repsSEXP, SEXP one_rollout_repsSEXP, SEXP total_budgetSEXP, SEXP rollout_policySEXP, SEXP max_rollout_turnsSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type roll(rollSEXP);
    Rcpp::traits::input_parameter< const int >::type legal_reps(legal_repsSEXP);
    Rcpp::traits::input_parameter< const int >::type apply_reps(apply_repsSEXP);
    Rcpp::traits::input_parameter< const int >::type one_rollout_reps(one_rollout_repsSEXP);
    Rcpp::traits::input_parameter< const int >::type total_budget(total_budgetSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type rollout_policy(rollout_policySEXP);
    Rcpp::traits::input_parameter< const int >::type max_rollout_turns(max_rollout_turnsSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_profile_rollout_runtime(board, roll, legal_reps, apply_reps, one_rollout_reps, total_budget, rollout_policy, max_rollout_turns, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_posterior_equal_choice
int bg_cpp_posterior_equal_choice(const Rcpp::IntegerVector& active_idx, const int spent);
RcppExport SEXP _backgammonr_bg_cpp_posterior_equal_choice(SEXP active_idxSEXP, SEXP spentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type active_idx(active_idxSEXP);
    Rcpp::traits::input_parameter< const int >::type spent(spentSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_posterior_equal_choice(active_idx, spent));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_posterior_thompson_choice
int bg_cpp_posterior_thompson_choice(const Rcpp::NumericMatrix& draw_mat, const Rcpp::NumericVector& allocation_count, const Rcpp::NumericVector& posterior_mean);
RcppExport SEXP _backgammonr_bg_cpp_posterior_thompson_choice(SEXP draw_matSEXP, SEXP allocation_countSEXP, SEXP posterior_meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type draw_mat(draw_matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type allocation_count(allocation_countSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type posterior_mean(posterior_meanSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_posterior_thompson_choice(draw_mat, allocation_count, posterior_mean));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_posterior_top_two_choice
int bg_cpp_posterior_top_two_choice(const Rcpp::NumericMatrix& draw_mat, const Rcpp::NumericVector& allocation_count, const double ttts_beta);
RcppExport SEXP _backgammonr_bg_cpp_posterior_top_two_choice(SEXP draw_matSEXP, SEXP allocation_countSEXP, SEXP ttts_betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type draw_mat(draw_matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type allocation_count(allocation_countSEXP);
    Rcpp::traits::input_parameter< const double >::type ttts_beta(ttts_betaSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_posterior_top_two_choice(draw_mat, allocation_count, ttts_beta));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_posterior_multi_sample_choice
int bg_cpp_posterior_multi_sample_choice(const Rcpp::NumericMatrix& draw_mat, const Rcpp::NumericVector& allocation_count, const Rcpp::NumericVector& posterior_mean);
RcppExport SEXP _backgammonr_bg_cpp_posterior_multi_sample_choice(SEXP draw_matSEXP, SEXP allocation_countSEXP, SEXP posterior_meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type draw_mat(draw_matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type allocation_count(allocation_countSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type posterior_mean(posterior_meanSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_posterior_multi_sample_choice(draw_mat, allocation_count, posterior_mean));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_posterior_forced_choice
int bg_cpp_posterior_forced_choice(const Rcpp::NumericVector& allocation_count, const int spent, const int forced_every, const int forced_min_allocations);
RcppExport SEXP _backgammonr_bg_cpp_posterior_forced_choice(SEXP allocation_countSEXP, SEXP spentSEXP, SEXP forced_everySEXP, SEXP forced_min_allocationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type allocation_count(allocation_countSEXP);
    Rcpp::traits::input_parameter< const int >::type spent(spentSEXP);
    Rcpp::traits::input_parameter< const int >::type forced_every(forced_everySEXP);
    Rcpp::traits::input_parameter< const int >::type forced_min_allocations(forced_min_allocationsSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_posterior_forced_choice(allocation_count, spent, forced_every, forced_min_allocations));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_posterior_update_active_set
Rcpp::LogicalVector bg_cpp_posterior_update_active_set(const Rcpp::LogicalVector& active, const Rcpp::NumericVector& posterior_mean, const Rcpp::NumericVector& posterior_sd, const Rcpp::NumericVector& allocation_count, const int min_allocations, const int keep_top, const double margin);
RcppExport SEXP _backgammonr_bg_cpp_posterior_update_active_set(SEXP activeSEXP, SEXP posterior_meanSEXP, SEXP posterior_sdSEXP, SEXP allocation_countSEXP, SEXP min_allocationsSEXP, SEXP keep_topSEXP, SEXP marginSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::LogicalVector& >::type active(activeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type posterior_mean(posterior_meanSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type posterior_sd(posterior_sdSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type allocation_count(allocation_countSEXP);
    Rcpp::traits::input_parameter< const int >::type min_allocations(min_allocationsSEXP);
    Rcpp::traits::input_parameter< const int >::type keep_top(keep_topSEXP);
    Rcpp::traits::input_parameter< const double >::type margin(marginSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_posterior_update_active_set(active, posterior_mean, posterior_sd, allocation_count, min_allocations, keep_top, margin));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_posterior_top_k_choice
int bg_cpp_posterior_top_k_choice(const Rcpp::NumericMatrix& draw_mat, const Rcpp::NumericVector& posterior_mean, const Rcpp::NumericVector& allocation_count, const int focus_top_k);
RcppExport SEXP _backgammonr_bg_cpp_posterior_top_k_choice(SEXP draw_matSEXP, SEXP posterior_meanSEXP, SEXP allocation_countSEXP, SEXP focus_top_kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type draw_mat(draw_matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type posterior_mean(posterior_meanSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type allocation_count(allocation_countSEXP);
    Rcpp::traits::input_parameter< const int >::type focus_top_k(focus_top_kSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_posterior_top_k_choice(draw_mat, posterior_mean, allocation_count, focus_top_k));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_posterior_sample_values
Rcpp::NumericMatrix bg_cpp_posterior_sample_values(const Rcpp::IntegerVector& allocation_count, const Rcpp::IntegerVector& wins, const Rcpp::IntegerVector& losses, const Rcpp::IntegerVector& single_loss, const Rcpp::IntegerVector& gammon_loss, const Rcpp::IntegerVector& backgammon_loss, const Rcpp::IntegerVector& unresolved, const Rcpp::IntegerVector& single_win, const Rcpp::IntegerVector& gammon_win, const Rcpp::IntegerVector& backgammon_win, const Rcpp::NumericVector& reward_sum, const Rcpp::NumericVector& reward_sum_sq, const std::string& reward_model, const std::string& posterior_model, const double unresolved_value, const Rcpp::List& posterior_prior, const int draws);
RcppExport SEXP _backgammonr_bg_cpp_posterior_sample_values(SEXP allocation_countSEXP, SEXP winsSEXP, SEXP lossesSEXP, SEXP single_lossSEXP, SEXP gammon_lossSEXP, SEXP backgammon_lossSEXP, SEXP unresolvedSEXP, SEXP single_winSEXP, SEXP gammon_winSEXP, SEXP backgammon_winSEXP, SEXP reward_sumSEXP, SEXP reward_sum_sqSEXP, SEXP reward_modelSEXP, SEXP posterior_modelSEXP, SEXP unresolved_valueSEXP, SEXP posterior_priorSEXP, SEXP drawsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type allocation_count(allocation_countSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type wins(winsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type losses(lossesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type single_loss(single_lossSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type gammon_loss(gammon_lossSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type backgammon_loss(backgammon_lossSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type unresolved(unresolvedSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type single_win(single_winSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type gammon_win(gammon_winSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type backgammon_win(backgammon_winSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type reward_sum(reward_sumSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type reward_sum_sq(reward_sum_sqSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type reward_model(reward_modelSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type posterior_model(posterior_modelSEXP);
    Rcpp::traits::input_parameter< const double >::type unresolved_value(unresolved_valueSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type posterior_prior(posterior_priorSEXP);
    Rcpp::traits::input_parameter< const int >::type draws(drawsSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_posterior_sample_values(allocation_count, wins, losses, single_loss, gammon_loss, backgammon_loss, unresolved, single_win, gammon_win, backgammon_win, reward_sum, reward_sum_sq, reward_model, posterior_model, unresolved_value, posterior_prior, draws));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_posterior_summary
Rcpp::DataFrame bg_cpp_posterior_summary(const Rcpp::IntegerVector& allocation_count, const Rcpp::IntegerVector& wins, const Rcpp::IntegerVector& losses, const Rcpp::IntegerVector& single_loss, const Rcpp::IntegerVector& gammon_loss, const Rcpp::IntegerVector& backgammon_loss, const Rcpp::IntegerVector& unresolved, const Rcpp::IntegerVector& single_win, const Rcpp::IntegerVector& gammon_win, const Rcpp::IntegerVector& backgammon_win, const Rcpp::NumericVector& reward_sum, const Rcpp::NumericVector& reward_sum_sq, const std::string& reward_model, const std::string& posterior_model, const double unresolved_value, const Rcpp::List& posterior_prior, const int draws);
RcppExport SEXP _backgammonr_bg_cpp_posterior_summary(SEXP allocation_countSEXP, SEXP winsSEXP, SEXP lossesSEXP, SEXP single_lossSEXP, SEXP gammon_lossSEXP, SEXP backgammon_lossSEXP, SEXP unresolvedSEXP, SEXP single_winSEXP, SEXP gammon_winSEXP, SEXP backgammon_winSEXP, SEXP reward_sumSEXP, SEXP reward_sum_sqSEXP, SEXP reward_modelSEXP, SEXP posterior_modelSEXP, SEXP unresolved_valueSEXP, SEXP posterior_priorSEXP, SEXP drawsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type allocation_count(allocation_countSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type wins(winsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type losses(lossesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type single_loss(single_lossSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type gammon_loss(gammon_lossSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type backgammon_loss(backgammon_lossSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type unresolved(unresolvedSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type single_win(single_winSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type gammon_win(gammon_winSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type backgammon_win(backgammon_winSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type reward_sum(reward_sumSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type reward_sum_sq(reward_sum_sqSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type reward_model(reward_modelSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type posterior_model(posterior_modelSEXP);
    Rcpp::traits::input_parameter< const double >::type unresolved_value(unresolved_valueSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type posterior_prior(posterior_priorSEXP);
    Rcpp::traits::input_parameter< const int >::type draws(drawsSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_posterior_summary(allocation_count, wins, losses, single_loss, gammon_loss, backgammon_loss, unresolved, single_win, gammon_win, backgammon_win, reward_sum, reward_sum_sq, reward_model, posterior_model, unresolved_value, posterior_prior, draws));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_reference_summary
Rcpp::DataFrame bg_cpp_reference_summary(const Rcpp::IntegerVector& allocation_count, const Rcpp::IntegerVector& unresolved, const Rcpp::NumericVector& reward_sum, const Rcpp::NumericVector& reward_sum_sq, const double prior_alpha, const double prior_beta);
RcppExport SEXP _backgammonr_bg_cpp_reference_summary(SEXP allocation_countSEXP, SEXP unresolvedSEXP, SEXP reward_sumSEXP, SEXP reward_sum_sqSEXP, SEXP prior_alphaSEXP, SEXP prior_betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type allocation_count(allocation_countSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type unresolved(unresolvedSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type reward_sum(reward_sumSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type reward_sum_sq(reward_sum_sqSEXP);
    Rcpp::traits::input_parameter< const double >::type prior_alpha(prior_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type prior_beta(prior_betaSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_reference_summary(allocation_count, unresolved, reward_sum, reward_sum_sq, prior_alpha, prior_beta));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_eval_path_metrics
Rcpp::List bg_cpp_eval_path_metrics(const Rcpp::IntegerVector& checkpoint, const Rcpp::NumericVector& runtime_seconds, const Rcpp::LogicalVector& top1_match, const Rcpp::LogicalVector& epsilon_optimal, const Rcpp::NumericVector& simple_regret, const Rcpp::NumericVector& recommended_prob_best);
RcppExport SEXP _backgammonr_bg_cpp_eval_path_metrics(SEXP checkpointSEXP, SEXP runtime_secondsSEXP, SEXP top1_matchSEXP, SEXP epsilon_optimalSEXP, SEXP simple_regretSEXP, SEXP recommended_prob_bestSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type checkpoint(checkpointSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type runtime_seconds(runtime_secondsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalVector& >::type top1_match(top1_matchSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalVector& >::type epsilon_optimal(epsilon_optimalSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type simple_regret(simple_regretSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type recommended_prob_best(recommended_prob_bestSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_eval_path_metrics(checkpoint, runtime_seconds, top1_match, epsilon_optimal, simple_regret, recommended_prob_best));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_calibration_summary
Rcpp::DataFrame bg_cpp_calibration_summary(const Rcpp::NumericVector& predicted_prob, const Rcpp::NumericVector& observed_top1, const int bins);
RcppExport SEXP _backgammonr_bg_cpp_calibration_summary(SEXP predicted_probSEXP, SEXP observed_top1SEXP, SEXP binsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type predicted_prob(predicted_probSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type observed_top1(observed_top1SEXP);
    Rcpp::traits::input_parameter< const int >::type bins(binsSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_calibration_summary(predicted_prob, observed_top1, bins));
    return rcpp_result_gen;
END_RCPP
}
// bg_cpp_rollout_blocks
Rcpp::List bg_cpp_rollout_blocks(const Rcpp::List& board, const Rcpp::List& legal_moves, const Rcpp::IntegerVector& candidate_index, const Rcpp::IntegerVector& block_rollouts, const Rcpp::IntegerVector& start_counts, const std::string& rollout_policy, const int max_rollout_turns, const double unresolved_value, const std::string& dice_mode, const bool crn, const int task_block_size, const int seed, const bool use_seed);
RcppExport SEXP _backgammonr_bg_cpp_rollout_blocks(SEXP boardSEXP, SEXP legal_movesSEXP, SEXP candidate_indexSEXP, SEXP block_rolloutsSEXP, SEXP start_countsSEXP, SEXP rollout_policySEXP, SEXP max_rollout_turnsSEXP, SEXP unresolved_valueSEXP, SEXP dice_modeSEXP, SEXP crnSEXP, SEXP task_block_sizeSEXP, SEXP seedSEXP, SEXP use_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type board(boardSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type legal_moves(legal_movesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type candidate_index(candidate_indexSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type block_rollouts(block_rolloutsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type start_counts(start_countsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type rollout_policy(rollout_policySEXP);
    Rcpp::traits::input_parameter< const int >::type max_rollout_turns(max_rollout_turnsSEXP);
    Rcpp::traits::input_parameter< const double >::type unresolved_value(unresolved_valueSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dice_mode(dice_modeSEXP);
    Rcpp::traits::input_parameter< const bool >::type crn(crnSEXP);
    Rcpp::traits::input_parameter< const int >::type task_block_size(task_block_sizeSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_seed(use_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bg_cpp_rollout_blocks(board, legal_moves, candidate_index, block_rollouts, start_counts, rollout_policy, max_rollout_turns, unresolved_value, dice_mode, crn, task_block_size, seed, use_seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_backgammonr_bg_cpp_benchmark_matchup_random", (DL_FUNC) &_backgammonr_bg_cpp_benchmark_matchup_random, 10},
    {"_backgammonr_bg_cpp_benchmark_matchup_scripted", (DL_FUNC) &_backgammonr_bg_cpp_benchmark_matchup_scripted, 11},
    {"_backgammonr_bg_cpp_benchmark_move_evaluators", (DL_FUNC) &_backgammonr_bg_cpp_benchmark_move_evaluators, 11},
    {"_backgammonr_bg_cpp_board_initial", (DL_FUNC) &_backgammonr_bg_cpp_board_initial, 1},
    {"_backgammonr_bg_cpp_board_clone", (DL_FUNC) &_backgammonr_bg_cpp_board_clone, 1},
    {"_backgammonr_bg_cpp_board_validate", (DL_FUNC) &_backgammonr_bg_cpp_board_validate, 1},
    {"_backgammonr_bg_cpp_roll_create", (DL_FUNC) &_backgammonr_bg_cpp_roll_create, 2},
    {"_backgammonr_bg_cpp_roll_dice", (DL_FUNC) &_backgammonr_bg_cpp_roll_dice, 3},
    {"_backgammonr_bg_cpp_terminal_score_class", (DL_FUNC) &_backgammonr_bg_cpp_terminal_score_class, 2},
    {"_backgammonr_bg_cpp_apply_move_sequence", (DL_FUNC) &_backgammonr_bg_cpp_apply_move_sequence, 2},
    {"_backgammonr_bg_cpp_play_turn_with_roll", (DL_FUNC) &_backgammonr_bg_cpp_play_turn_with_roll, 5},
    {"_backgammonr_bg_cpp_play_turn_random", (DL_FUNC) &_backgammonr_bg_cpp_play_turn_random, 4},
    {"_backgammonr_bg_cpp_play_game_random", (DL_FUNC) &_backgammonr_bg_cpp_play_game_random, 5},
    {"_backgammonr_bg_cpp_play_game_scripted", (DL_FUNC) &_backgammonr_bg_cpp_play_game_scripted, 6},
    {"_backgammonr_bg_cpp_play_game_matchup_random", (DL_FUNC) &_backgammonr_bg_cpp_play_game_matchup_random, 6},
    {"_backgammonr_bg_cpp_play_game_matchup_scripted", (DL_FUNC) &_backgammonr_bg_cpp_play_game_matchup_scripted, 7},
    {"_backgammonr_bg_cpp_play_turn_with_roll_rollout", (DL_FUNC) &_backgammonr_bg_cpp_play_turn_with_roll_rollout, 8},
    {"_backgammonr_bg_cpp_play_turn_random_rollout", (DL_FUNC) &_backgammonr_bg_cpp_play_turn_random_rollout, 7},
    {"_backgammonr_bg_cpp_play_game_random_rollout", (DL_FUNC) &_backgammonr_bg_cpp_play_game_random_rollout, 8},
    {"_backgammonr_bg_cpp_play_game_scripted_rollout", (DL_FUNC) &_backgammonr_bg_cpp_play_game_scripted_rollout, 9},
    {"_backgammonr_bg_cpp_play_game_matchup_random_rollout", (DL_FUNC) &_backgammonr_bg_cpp_play_game_matchup_random_rollout, 9},
    {"_backgammonr_bg_cpp_play_game_matchup_scripted_rollout", (DL_FUNC) &_backgammonr_bg_cpp_play_game_matchup_scripted_rollout, 10},
    {"_backgammonr_bg_cpp_move_step_create", (DL_FUNC) &_backgammonr_bg_cpp_move_step_create, 4},
    {"_backgammonr_bg_cpp_move_sequence_create", (DL_FUNC) &_backgammonr_bg_cpp_move_sequence_create, 2},
    {"_backgammonr_bg_cpp_move_sequence_create_with_roll", (DL_FUNC) &_backgammonr_bg_cpp_move_sequence_create_with_roll, 3},
    {"_backgammonr_bg_cpp_legal_moves", (DL_FUNC) &_backgammonr_bg_cpp_legal_moves, 3},
    {"_backgammonr_bg_cpp_random_move_choice", (DL_FUNC) &_backgammonr_bg_cpp_random_move_choice, 3},
    {"_backgammonr_bg_cpp_heuristic_board_score", (DL_FUNC) &_backgammonr_bg_cpp_heuristic_board_score, 3},
    {"_backgammonr_bg_cpp_heuristic_board_features", (DL_FUNC) &_backgammonr_bg_cpp_heuristic_board_features, 2},
    {"_backgammonr_bg_cpp_heuristic_move_choice", (DL_FUNC) &_backgammonr_bg_cpp_heuristic_move_choice, 3},
    {"_backgammonr_bg_cpp_thompson_rollout_move_evaluate", (DL_FUNC) &_backgammonr_bg_cpp_thompson_rollout_move_evaluate, 7},
    {"_backgammonr_bg_cpp_thompson_rollout_move_choice", (DL_FUNC) &_backgammonr_bg_cpp_thompson_rollout_move_choice, 7},
    {"_backgammonr_bg_cpp_rollout_move_evaluate", (DL_FUNC) &_backgammonr_bg_cpp_rollout_move_evaluate, 7},
    {"_backgammonr_bg_cpp_rollout_move_choice", (DL_FUNC) &_backgammonr_bg_cpp_rollout_move_choice, 7},
    {"_backgammonr_bg_cpp_simulate_matchup_random", (DL_FUNC) &_backgammonr_bg_cpp_simulate_matchup_random, 7},
    {"_backgammonr_bg_cpp_simulate_matchup_scripted", (DL_FUNC) &_backgammonr_bg_cpp_simulate_matchup_scripted, 8},
    {"_backgammonr_bg_cpp_simulate_matchup_random_rollout", (DL_FUNC) &_backgammonr_bg_cpp_simulate_matchup_random_rollout, 10},
    {"_backgammonr_bg_cpp_simulate_matchup_scripted_rollout", (DL_FUNC) &_backgammonr_bg_cpp_simulate_matchup_scripted_rollout, 11},
    {"_backgammonr_bg_cpp_allocation_evaluate", (DL_FUNC) &_backgammonr_bg_cpp_allocation_evaluate, 16},
    {"_backgammonr_bg_cpp_allocation_evaluate_trace", (DL_FUNC) &_backgammonr_bg_cpp_allocation_evaluate_trace, 17},
    {"_backgammonr_bg_cpp_profile_rollout_runtime", (DL_FUNC) &_backgammonr_bg_cpp_profile_rollout_runtime, 10},
    {"_backgammonr_bg_cpp_posterior_equal_choice", (DL_FUNC) &_backgammonr_bg_cpp_posterior_equal_choice, 2},
    {"_backgammonr_bg_cpp_posterior_thompson_choice", (DL_FUNC) &_backgammonr_bg_cpp_posterior_thompson_choice, 3},
    {"_backgammonr_bg_cpp_posterior_top_two_choice", (DL_FUNC) &_backgammonr_bg_cpp_posterior_top_two_choice, 3},
    {"_backgammonr_bg_cpp_posterior_multi_sample_choice", (DL_FUNC) &_backgammonr_bg_cpp_posterior_multi_sample_choice, 3},
    {"_backgammonr_bg_cpp_posterior_forced_choice", (DL_FUNC) &_backgammonr_bg_cpp_posterior_forced_choice, 4},
    {"_backgammonr_bg_cpp_posterior_update_active_set", (DL_FUNC) &_backgammonr_bg_cpp_posterior_update_active_set, 7},
    {"_backgammonr_bg_cpp_posterior_top_k_choice", (DL_FUNC) &_backgammonr_bg_cpp_posterior_top_k_choice, 4},
    {"_backgammonr_bg_cpp_posterior_sample_values", (DL_FUNC) &_backgammonr_bg_cpp_posterior_sample_values, 17},
    {"_backgammonr_bg_cpp_posterior_summary", (DL_FUNC) &_backgammonr_bg_cpp_posterior_summary, 17},
    {"_backgammonr_bg_cpp_reference_summary", (DL_FUNC) &_backgammonr_bg_cpp_reference_summary, 6},
    {"_backgammonr_bg_cpp_eval_path_metrics", (DL_FUNC) &_backgammonr_bg_cpp_eval_path_metrics, 6},
    {"_backgammonr_bg_cpp_calibration_summary", (DL_FUNC) &_backgammonr_bg_cpp_calibration_summary, 3},
    {"_backgammonr_bg_cpp_rollout_blocks", (DL_FUNC) &_backgammonr_bg_cpp_rollout_blocks, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_backgammonr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
