# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bg_cpp_allocation_evaluate <- function(board, legal_moves, method, total_budget, rollout_policy, max_rollout_turns, unresolved_value, initial_allocations, ucb_exploration, prior_alpha, prior_beta, dice_mode, crn, fast_diagnostics, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_allocation_evaluate`, board, legal_moves, method, total_budget, rollout_policy, max_rollout_turns, unresolved_value, initial_allocations, ucb_exploration, prior_alpha, prior_beta, dice_mode, crn, fast_diagnostics, seed, use_seed)
}

bg_cpp_allocation_evaluate_trace <- function(board, legal_moves, method, total_budget, rollout_policy, max_rollout_turns, unresolved_value, initial_allocations, ucb_exploration, prior_alpha, prior_beta, dice_mode, crn, fast_diagnostics, trace_every, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_allocation_evaluate_trace`, board, legal_moves, method, total_budget, rollout_policy, max_rollout_turns, unresolved_value, initial_allocations, ucb_exploration, prior_alpha, prior_beta, dice_mode, crn, fast_diagnostics, trace_every, seed, use_seed)
}

bg_cpp_profile_rollout_runtime <- function(board, roll, legal_reps, apply_reps, one_rollout_reps, total_budget, rollout_policy, max_rollout_turns, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_profile_rollout_runtime`, board, roll, legal_reps, apply_reps, one_rollout_reps, total_budget, rollout_policy, max_rollout_turns, seed, use_seed)
}

bg_cpp_benchmark_matchup_random <- function(board, n_games, max_turns, player1_selection, player2_selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_benchmark_matchup_random`, board, n_games, max_turns, player1_selection, player2_selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed)
}

bg_cpp_benchmark_matchup_scripted <- function(board, rolls, n_games, max_turns, player1_selection, player2_selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_benchmark_matchup_scripted`, board, rolls, n_games, max_turns, player1_selection, player2_selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed)
}

bg_cpp_benchmark_move_evaluators <- function(cases, methods, reference_method, rollout_budget, rollout_policy, max_rollout_turns, reference_rollout_budget, reference_rollout_policy, reference_max_rollout_turns, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_benchmark_move_evaluators`, cases, methods, reference_method, rollout_budget, rollout_policy, max_rollout_turns, reference_rollout_budget, reference_rollout_policy, reference_max_rollout_turns, seed, use_seed)
}

bg_cpp_board_initial <- function(turn = 1L) {
    .Call(`_backgammonr_bg_cpp_board_initial`, turn)
}

bg_cpp_board_clone <- function(board) {
    .Call(`_backgammonr_bg_cpp_board_clone`, board)
}

bg_cpp_board_validate <- function(board) {
    .Call(`_backgammonr_bg_cpp_board_validate`, board)
}

bg_cpp_roll_create <- function(die1, die2) {
    .Call(`_backgammonr_bg_cpp_roll_create`, die1, die2)
}

bg_cpp_roll_dice <- function(n, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_roll_dice`, n, seed, use_seed)
}

bg_cpp_apply_move_sequence <- function(board, move_sequence) {
    .Call(`_backgammonr_bg_cpp_apply_move_sequence`, board, move_sequence)
}

bg_cpp_play_turn_with_roll <- function(board, roll, selection, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_play_turn_with_roll`, board, roll, selection, seed, use_seed)
}

bg_cpp_play_turn_random <- function(board, selection, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_play_turn_random`, board, selection, seed, use_seed)
}

bg_cpp_play_game_random <- function(board, max_turns, selection, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_play_game_random`, board, max_turns, selection, seed, use_seed)
}

bg_cpp_play_game_scripted <- function(board, rolls, max_turns, selection, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_play_game_scripted`, board, rolls, max_turns, selection, seed, use_seed)
}

bg_cpp_play_game_matchup_random <- function(board, max_turns, player1_selection, player2_selection, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_play_game_matchup_random`, board, max_turns, player1_selection, player2_selection, seed, use_seed)
}

bg_cpp_play_game_matchup_scripted <- function(board, rolls, max_turns, player1_selection, player2_selection, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_play_game_matchup_scripted`, board, rolls, max_turns, player1_selection, player2_selection, seed, use_seed)
}

bg_cpp_play_turn_with_roll_rollout <- function(board, roll, selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_play_turn_with_roll_rollout`, board, roll, selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed)
}

bg_cpp_play_turn_random_rollout <- function(board, selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_play_turn_random_rollout`, board, selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed)
}

bg_cpp_play_game_random_rollout <- function(board, max_turns, selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_play_game_random_rollout`, board, max_turns, selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed)
}

bg_cpp_play_game_scripted_rollout <- function(board, rolls, max_turns, selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_play_game_scripted_rollout`, board, rolls, max_turns, selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed)
}

bg_cpp_play_game_matchup_random_rollout <- function(board, max_turns, player1_selection, player2_selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_play_game_matchup_random_rollout`, board, max_turns, player1_selection, player2_selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed)
}

bg_cpp_play_game_matchup_scripted_rollout <- function(board, rolls, max_turns, player1_selection, player2_selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_play_game_matchup_scripted_rollout`, board, rolls, max_turns, player1_selection, player2_selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed)
}

bg_cpp_heuristic_board_score <- function(board, player, selection) {
    .Call(`_backgammonr_bg_cpp_heuristic_board_score`, board, player, selection)
}

bg_cpp_heuristic_board_features <- function(board, player) {
    .Call(`_backgammonr_bg_cpp_heuristic_board_features`, board, player)
}

bg_cpp_heuristic_move_choice <- function(board, legal_moves, selection) {
    .Call(`_backgammonr_bg_cpp_heuristic_move_choice`, board, legal_moves, selection)
}

bg_cpp_move_step_create <- function(from, to, die, hit = FALSE) {
    .Call(`_backgammonr_bg_cpp_move_step_create`, from, to, die, hit)
}

bg_cpp_move_sequence_create <- function(player, steps) {
    .Call(`_backgammonr_bg_cpp_move_sequence_create`, player, steps)
}

bg_cpp_move_sequence_create_with_roll <- function(player, steps, roll) {
    .Call(`_backgammonr_bg_cpp_move_sequence_create_with_roll`, player, steps, roll)
}

bg_cpp_legal_moves <- function(board, player, roll) {
    .Call(`_backgammonr_bg_cpp_legal_moves`, board, player, roll)
}

bg_cpp_random_move_choice <- function(legal_moves, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_random_move_choice`, legal_moves, seed, use_seed)
}

bg_cpp_rollout_move_evaluate <- function(board, legal_moves, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_rollout_move_evaluate`, board, legal_moves, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed)
}

bg_cpp_rollout_move_choice <- function(board, legal_moves, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_rollout_move_choice`, board, legal_moves, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed)
}

bg_cpp_simulate_matchup_random <- function(board, n_games, max_turns, player1_selection, player2_selection, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_simulate_matchup_random`, board, n_games, max_turns, player1_selection, player2_selection, seed, use_seed)
}

bg_cpp_simulate_matchup_scripted <- function(board, rolls, n_games, max_turns, player1_selection, player2_selection, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_simulate_matchup_scripted`, board, rolls, n_games, max_turns, player1_selection, player2_selection, seed, use_seed)
}

bg_cpp_simulate_matchup_random_rollout <- function(board, n_games, max_turns, player1_selection, player2_selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_simulate_matchup_random_rollout`, board, n_games, max_turns, player1_selection, player2_selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed)
}

bg_cpp_simulate_matchup_scripted_rollout <- function(board, rolls, n_games, max_turns, player1_selection, player2_selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_simulate_matchup_scripted_rollout`, board, rolls, n_games, max_turns, player1_selection, player2_selection, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed)
}

bg_cpp_thompson_rollout_move_evaluate <- function(board, legal_moves, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_thompson_rollout_move_evaluate`, board, legal_moves, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed)
}

bg_cpp_thompson_rollout_move_choice <- function(board, legal_moves, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed) {
    .Call(`_backgammonr_bg_cpp_thompson_rollout_move_choice`, board, legal_moves, rollout_budget, rollout_policy, max_rollout_turns, seed, use_seed)
}

